/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppOfflineRouteImport } from './routes/_app/offline'
import { Route as AppRecentRouteImport } from './routes/_app/recent'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSharedRouteImport } from './routes/_app/shared'
import { Route as AppSpamRouteImport } from './routes/_app/spam'
import { Route as AppStarredRouteImport } from './routes/_app/starred'
import { Route as AppStorageRouteImport } from './routes/_app/storage'
import { Route as AppTrashRouteImport } from './routes/_app/trash'
import { Route as AppFolderFolderIdRouteImport } from './routes/_app/folder.$folderId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOfflineRoute = AppOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => AppRoute,
} as any)
const AppRecentRoute = AppRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedRoute = AppSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => AppRoute,
} as any)
const AppSpamRoute = AppSpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => AppRoute,
} as any)
const AppStarredRoute = AppStarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppFolderFolderIdRoute = AppFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/offline': typeof AppOfflineRoute
  '/recent': typeof AppRecentRoute
  '/settings': typeof AppSettingsRoute
  '/shared': typeof AppSharedRoute
  '/spam': typeof AppSpamRoute
  '/starred': typeof AppStarredRoute
  '/storage': typeof AppStorageRoute
  '/trash': typeof AppTrashRoute
  '/folder/$folderId': typeof AppFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/offline': typeof AppOfflineRoute
  '/recent': typeof AppRecentRoute
  '/settings': typeof AppSettingsRoute
  '/shared': typeof AppSharedRoute
  '/spam': typeof AppSpamRoute
  '/starred': typeof AppStarredRoute
  '/storage': typeof AppStorageRoute
  '/trash': typeof AppTrashRoute
  '/': typeof AppIndexRoute
  '/folder/$folderId': typeof AppFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/offline': typeof AppOfflineRoute
  '/_app/recent': typeof AppRecentRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shared': typeof AppSharedRoute
  '/_app/spam': typeof AppSpamRoute
  '/_app/starred': typeof AppStarredRoute
  '/_app/storage': typeof AppStorageRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/': typeof AppIndexRoute
  '/_app/folder/$folderId': typeof AppFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offline'
    | '/recent'
    | '/settings'
    | '/shared'
    | '/spam'
    | '/starred'
    | '/storage'
    | '/trash'
    | '/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/offline'
    | '/recent'
    | '/settings'
    | '/shared'
    | '/spam'
    | '/starred'
    | '/storage'
    | '/trash'
    | '/'
    | '/folder/$folderId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/offline'
    | '/_app/recent'
    | '/_app/settings'
    | '/_app/shared'
    | '/_app/spam'
    | '/_app/starred'
    | '/_app/storage'
    | '/_app/trash'
    | '/_app/'
    | '/_app/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offline': {
      id: '/_app/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof AppOfflineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recent': {
      id: '/_app/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AppRecentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared': {
      id: '/_app/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof AppSharedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spam': {
      id: '/_app/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof AppSpamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/starred': {
      id: '/_app/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof AppStarredRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/folder/$folderId': {
      id: '/_app/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof AppFolderFolderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOfflineRoute: typeof AppOfflineRoute
  AppRecentRoute: typeof AppRecentRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSharedRoute: typeof AppSharedRoute
  AppSpamRoute: typeof AppSpamRoute
  AppStarredRoute: typeof AppStarredRoute
  AppStorageRoute: typeof AppStorageRoute
  AppTrashRoute: typeof AppTrashRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFolderFolderIdRoute: typeof AppFolderFolderIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOfflineRoute: AppOfflineRoute,
  AppRecentRoute: AppRecentRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSharedRoute: AppSharedRoute,
  AppSpamRoute: AppSpamRoute,
  AppStarredRoute: AppStarredRoute,
  AppStorageRoute: AppStorageRoute,
  AppTrashRoute: AppTrashRoute,
  AppIndexRoute: AppIndexRoute,
  AppFolderFolderIdRoute: AppFolderFolderIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
